<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="8" ignored="8" total="26" passed="6" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-14T00:48:54 IST" name="Ecommerce Automation Suite" finished-at="2025-09-14T01:06:51 IST" duration-ms="1077055">
    <groups>
    </groups>
    <test started-at="2025-09-14T00:48:54 IST" name="Chrome Tests" finished-at="2025-09-14T01:05:46 IST" duration-ms="1012087">
      <class name="ramchavantestautomation.Tests.LoginPageTest">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:48:55 IST" name="startTest" finished-at="2025-09-14T00:49:28 IST" duration-ms="32441" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:49:28 IST" name="invalidLoginTest" data-provider="invalidLoginData" finished-at="2025-09-14T00:50:11 IST" duration-ms="42908" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[bad1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:50:11 IST" name="captureResult" finished-at="2025-09-14T00:50:54 IST" duration-ms="43104" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalidLoginTest status=SUCCESS method=LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:50:54 IST" name="startTest" finished-at="2025-09-14T00:51:37 IST" duration-ms="42914" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:51:37 IST" name="invalidLoginTest" data-provider="invalidLoginData" finished-at="2025-09-14T00:52:20 IST" duration-ms="42916" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[bad2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[short]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:52:20 IST" name="captureResult" finished-at="2025-09-14T00:53:03 IST" duration-ms="43186" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalidLoginTest status=SUCCESS method=LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:53:03 IST" name="startTest" finished-at="2025-09-14T00:53:46 IST" duration-ms="42686" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:53:46 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T00:54:29 IST" duration-ms="42900" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:54:29 IST" name="captureResult" finished-at="2025-09-14T00:55:12 IST" duration-ms="43181" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:55:12 IST" name="startTest" finished-at="2025-09-14T00:55:55 IST" duration-ms="42906" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:55:55 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T00:56:38 IST" duration-ms="43009" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:56:38 IST" name="captureResult" finished-at="2025-09-14T00:57:21 IST" duration-ms="43064" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:57:21 IST" name="startTest" finished-at="2025-09-14T00:58:04 IST" duration-ms="42921" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:58:04 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T00:58:47 IST" duration-ms="43008" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:58:47 IST" name="captureResult" finished-at="2025-09-14T00:58:47 IST" duration-ms="2" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=FAILURE method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "ramchavantestautomation.WebActions.WebAction.captureScreenshot(String)" because "this.action" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "ramchavantestautomation.WebActions.WebAction.captureScreenshot(String)" because "this.action" is null
at ramchavantestautomation.Tests.BaseTest.captureResult(BaseTest.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)
at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:802)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:778)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:58:47 IST" name="startTest" finished-at="2025-09-14T00:59:19 IST" duration-ms="32400" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T00:59:19 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T01:00:02 IST" duration-ms="43034" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T01:00:02 IST" name="captureResult" finished-at="2025-09-14T01:00:45 IST" duration-ms="42898" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T01:00:45 IST" name="startTest" finished-at="2025-09-14T01:01:28 IST" duration-ms="42894" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T01:01:28 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T01:02:11 IST" duration-ms="43079" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T01:02:11 IST" name="captureResult" finished-at="2025-09-14T01:02:54 IST" duration-ms="42894" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T01:02:54 IST" name="startTest" finished-at="2025-09-14T01:03:37 IST" duration-ms="42986" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T01:03:37 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T01:04:20 IST" duration-ms="43103" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca]" started-at="2025-09-14T01:04:20 IST" name="captureResult" finished-at="2025-09-14T01:04:20 IST" duration-ms="1" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=FAILURE method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@1aa7ecca] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "ramchavantestautomation.WebActions.WebAction.captureScreenshot(String)" because "this.action" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "ramchavantestautomation.WebActions.WebAction.captureScreenshot(String)" because "this.action" is null
at ramchavantestautomation.Tests.BaseTest.captureResult(BaseTest.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)
at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:802)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:778)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
      </class> <!-- ramchavantestautomation.Tests.LoginPageTest -->
      <class name="ramchavantestautomation.Tests.SampleUnitTest">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@6b81ce95]" started-at="2025-09-14T01:04:20 IST" name="startTest" finished-at="2025-09-14T01:05:03 IST" duration-ms="42882" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.SampleUnitTest.alwaysPass()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="alwaysPass()[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@6b81ce95]" started-at="2025-09-14T01:05:03 IST" name="alwaysPass" finished-at="2025-09-14T01:05:03 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- alwaysPass -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@6b81ce95]" started-at="2025-09-14T01:05:03 IST" name="captureResult" finished-at="2025-09-14T01:05:46 IST" duration-ms="42949" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=alwaysPass status=SUCCESS method=SampleUnitTest.alwaysPass()[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@6b81ce95] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
      </class> <!-- ramchavantestautomation.Tests.SampleUnitTest -->
    </test> <!-- Chrome Tests -->
    <test started-at="2025-09-14T00:48:54 IST" name="Firefox Tests" finished-at="2025-09-14T01:06:51 IST" duration-ms="1077055">
      <class name="ramchavantestautomation.Tests.LoginPageTest">
        <test-method is-config="true" signature="setUpSuite(java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:48:46 IST" name="setUpSuite" finished-at="2025-09-14T00:48:54 IST" duration-ms="7701" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSuite -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:48:55 IST" name="startTest" finished-at="2025-09-14T00:49:39 IST" duration-ms="43168" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:49:39 IST" name="invalidLoginTest" data-provider="invalidLoginData" finished-at="2025-09-14T00:50:22 IST" duration-ms="43024" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[bad1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:50:22 IST" name="captureResult" finished-at="2025-09-14T00:51:04 IST" duration-ms="42968" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalidLoginTest status=SUCCESS method=LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:51:04 IST" name="startTest" finished-at="2025-09-14T00:51:47 IST" duration-ms="42900" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:51:47 IST" name="invalidLoginTest" data-provider="invalidLoginData" finished-at="2025-09-14T00:52:30 IST" duration-ms="43033" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[bad2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[short]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:52:30 IST" name="captureResult" finished-at="2025-09-14T00:53:14 IST" duration-ms="43276" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalidLoginTest status=SUCCESS method=LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:53:14 IST" name="startTest" finished-at="2025-09-14T00:53:56 IST" duration-ms="42351" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:53:56 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T00:54:39 IST" duration-ms="43025" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:54:39 IST" name="captureResult" finished-at="2025-09-14T00:55:23 IST" duration-ms="43094" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:55:23 IST" name="startTest" finished-at="2025-09-14T00:56:05 IST" duration-ms="42948" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:56:05 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T00:56:48 IST" duration-ms="43020" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:56:48 IST" name="captureResult" finished-at="2025-09-14T00:57:32 IST" duration-ms="43012" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:57:32 IST" name="startTest" finished-at="2025-09-14T00:58:14 IST" duration-ms="42898" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:58:14 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T00:58:57 IST" duration-ms="43094" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:58:57 IST" name="captureResult" finished-at="2025-09-14T00:59:51 IST" duration-ms="53841" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=FAILURE method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T00:59:51 IST" name="startTest" finished-at="2025-09-14T01:00:34 IST" duration-ms="42939" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T01:00:34 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T01:01:17 IST" duration-ms="42998" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T01:01:17 IST" name="captureResult" finished-at="2025-09-14T01:02:00 IST" duration-ms="42935" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T01:02:00 IST" name="startTest" finished-at="2025-09-14T01:02:43 IST" duration-ms="42965" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T01:02:43 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T01:03:26 IST" duration-ms="42998" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T01:03:26 IST" name="captureResult" finished-at="2025-09-14T01:04:09 IST" duration-ms="42983" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T01:04:09 IST" name="startTest" finished-at="2025-09-14T01:04:52 IST" duration-ms="42994" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T01:04:52 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-14T01:05:35 IST" duration-ms="42975" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T01:05:35 IST" name="captureResult" finished-at="2025-09-14T01:06:08 IST" duration-ms="32533" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=FAILURE method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="tearDownSuite()[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@5c6648b0]" started-at="2025-09-14T01:06:51 IST" name="tearDownSuite" finished-at="2025-09-14T01:06:52 IST" duration-ms="960" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- ramchavantestautomation.Tests.LoginPageTest -->
      <class name="ramchavantestautomation.Tests.SampleUnitTest">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@6f1de4c7]" started-at="2025-09-14T01:06:08 IST" name="startTest" finished-at="2025-09-14T01:06:29 IST" duration-ms="21643" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.SampleUnitTest.alwaysPass()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="alwaysPass()[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@6f1de4c7]" started-at="2025-09-14T01:06:29 IST" name="alwaysPass" finished-at="2025-09-14T01:06:29 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- alwaysPass -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@6f1de4c7]" started-at="2025-09-14T01:06:29 IST" name="captureResult" finished-at="2025-09-14T01:06:51 IST" duration-ms="21530" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=alwaysPass status=SUCCESS method=SampleUnitTest.alwaysPass()[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@6f1de4c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
      </class> <!-- ramchavantestautomation.Tests.SampleUnitTest -->
    </test> <!-- Firefox Tests -->
  </suite> <!-- Ecommerce Automation Suite -->
</testng-results>
