<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="8" ignored="0" total="18" passed="6" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-13T22:54:57 IST" name="Ecommerce Automation Suite" finished-at="2025-09-13T23:13:11 IST" duration-ms="1094105">
    <groups>
    </groups>
    <test started-at="2025-09-13T22:54:57 IST" name="Firefox Tests" finished-at="2025-09-13T23:13:00 IST" duration-ms="1083554">
      <class name="ramchavantestautomation.Tests.LoginPageTest">
        <test-method is-config="true" signature="setUpSuite(java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T22:54:48 IST" name="setUpSuite" finished-at="2025-09-13T22:54:56 IST" duration-ms="8277" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSuite -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T22:54:58 IST" name="startTest" finished-at="2025-09-13T22:55:30 IST" duration-ms="31604" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T22:55:30 IST" name="invalidLoginTest" data-provider="invalidLoginData" finished-at="2025-09-13T22:56:12 IST" duration-ms="42045" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[bad1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T22:56:12 IST" name="captureResult" finished-at="2025-09-13T22:56:54 IST" duration-ms="41884" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalidLoginTest status=SUCCESS method=LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T22:56:54 IST" name="startTest" finished-at="2025-09-13T22:57:36 IST" duration-ms="41992" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T22:57:36 IST" name="invalidLoginTest" data-provider="invalidLoginData" finished-at="2025-09-13T22:58:18 IST" duration-ms="41965" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[bad2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[short]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T22:58:18 IST" name="captureResult" finished-at="2025-09-13T22:59:00 IST" duration-ms="41977" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalidLoginTest status=SUCCESS method=LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T22:59:00 IST" name="startTest" finished-at="2025-09-13T22:59:42 IST" duration-ms="41845" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T22:59:42 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:00:23 IST" duration-ms="41980" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:00:23 IST" name="captureResult" finished-at="2025-09-13T23:01:05 IST" duration-ms="41959" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:01:05 IST" name="startTest" finished-at="2025-09-13T23:01:47 IST" duration-ms="41989" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:01:47 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:02:30 IST" duration-ms="42063" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:02:30 IST" name="captureResult" finished-at="2025-09-13T23:03:11 IST" duration-ms="41951" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:03:11 IST" name="startTest" finished-at="2025-09-13T23:03:53 IST" duration-ms="42004" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:03:53 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:04:35 IST" duration-ms="41992" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:04:35 IST" name="captureResult" finished-at="2025-09-13T23:05:18 IST" duration-ms="42120" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=FAILURE method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:05:18 IST" name="startTest" finished-at="2025-09-13T23:06:00 IST" duration-ms="42002" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:06:00 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:06:42 IST" duration-ms="41986" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:06:42 IST" name="captureResult" finished-at="2025-09-13T23:07:24 IST" duration-ms="42169" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:07:24 IST" name="startTest" finished-at="2025-09-13T23:08:06 IST" duration-ms="41935" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:08:06 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:08:48 IST" duration-ms="41967" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:08:48 IST" name="captureResult" finished-at="2025-09-13T23:09:30 IST" duration-ms="42155" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:09:30 IST" name="startTest" finished-at="2025-09-13T23:10:12 IST" duration-ms="41981" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:10:12 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:10:54 IST" duration-ms="42050" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:10:54 IST" name="captureResult" finished-at="2025-09-13T23:11:36 IST" duration-ms="42097" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=FAILURE method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="tearDownSuite()[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@291caca8]" started-at="2025-09-13T23:13:11 IST" name="tearDownSuite" finished-at="2025-09-13T23:13:11 IST" duration-ms="537" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- ramchavantestautomation.Tests.LoginPageTest -->
      <class name="ramchavantestautomation.Tests.SampleUnitTest">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@385e9564]" started-at="2025-09-13T23:11:36 IST" name="startTest" finished-at="2025-09-13T23:12:18 IST" duration-ms="41990" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.SampleUnitTest.alwaysPass()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="alwaysPass()[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@385e9564]" started-at="2025-09-13T23:12:18 IST" name="alwaysPass" finished-at="2025-09-13T23:12:18 IST" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- alwaysPass -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@385e9564]" started-at="2025-09-13T23:12:18 IST" name="captureResult" finished-at="2025-09-13T23:13:00 IST" duration-ms="42112" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=alwaysPass status=SUCCESS method=SampleUnitTest.alwaysPass()[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@385e9564] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
      </class> <!-- ramchavantestautomation.Tests.SampleUnitTest -->
    </test> <!-- Firefox Tests -->
    <test started-at="2025-09-13T22:54:57 IST" name="Chrome Tests" finished-at="2025-09-13T23:13:11 IST" duration-ms="1094105">
      <class name="ramchavantestautomation.Tests.LoginPageTest">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T22:54:58 IST" name="startTest" finished-at="2025-09-13T22:55:40 IST" duration-ms="42090" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T22:55:40 IST" name="invalidLoginTest" data-provider="invalidLoginData" finished-at="2025-09-13T22:56:22 IST" duration-ms="42011" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[bad1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T22:56:22 IST" name="captureResult" finished-at="2025-09-13T22:57:04 IST" duration-ms="41929" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalidLoginTest status=SUCCESS method=LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T22:57:04 IST" name="startTest" finished-at="2025-09-13T22:57:46 IST" duration-ms="41974" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T22:57:46 IST" name="invalidLoginTest" data-provider="invalidLoginData" finished-at="2025-09-13T22:58:28 IST" duration-ms="42019" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[bad2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[short]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T22:58:28 IST" name="captureResult" finished-at="2025-09-13T22:59:10 IST" duration-ms="41970" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalidLoginTest status=SUCCESS method=LoginPageTest.invalidLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T22:59:10 IST" name="startTest" finished-at="2025-09-13T22:59:52 IST" duration-ms="41796" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T22:59:52 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:00:34 IST" duration-ms="41975" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:00:34 IST" name="captureResult" finished-at="2025-09-13T23:01:16 IST" duration-ms="42028" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:01:16 IST" name="startTest" finished-at="2025-09-13T23:01:58 IST" duration-ms="41949" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:01:58 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:02:40 IST" duration-ms="42055" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:02:40 IST" name="captureResult" finished-at="2025-09-13T23:03:22 IST" duration-ms="41993" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:03:22 IST" name="startTest" finished-at="2025-09-13T23:04:04 IST" duration-ms="41985" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:04:04 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:04:46 IST" duration-ms="42025" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user1@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user1@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:04:46 IST" name="captureResult" finished-at="2025-09-13T23:05:28 IST" duration-ms="42078" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=FAILURE method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:05:28 IST" name="startTest" finished-at="2025-09-13T23:06:10 IST" duration-ms="41991" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:06:10 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:06:52 IST" duration-ms="42082" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:06:52 IST" name="captureResult" finished-at="2025-09-13T23:07:34 IST" duration-ms="42058" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:07:34 IST" name="startTest" finished-at="2025-09-13T23:08:16 IST" duration-ms="42002" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method retried="true" signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:08:16 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:08:58 IST" duration-ms="41932" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:08:58 IST" name="captureResult" finished-at="2025-09-13T23:09:40 IST" duration-ms="42134" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=SKIP method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:09:40 IST" name="startTest" finished-at="2025-09-13T23:10:22 IST" duration-ms="41976" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.LoginPageTest.validLoginTest(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:10:22 IST" name="validLoginTest" data-provider="loginTestData" finished-at="2025-09-13T23:11:04 IST" duration-ms="42150" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[user2@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login method returned false for: user2@test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login method returned false for: user2@test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at ramchavantestautomation.Tests.LoginPageTest.validLoginTest(LoginPageTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9]" started-at="2025-09-13T23:11:04 IST" name="captureResult" finished-at="2025-09-13T23:11:46 IST" duration-ms="41990" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLoginTest status=FAILURE method=LoginPageTest.validLoginTest(java.lang.String,java.lang.String)[pri:0, instance:ramchavantestautomation.Tests.LoginPageTest@4116aac9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
      </class> <!-- ramchavantestautomation.Tests.LoginPageTest -->
      <class name="ramchavantestautomation.Tests.SampleUnitTest">
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@489115ef]" started-at="2025-09-13T23:11:46 IST" name="startTest" finished-at="2025-09-13T23:12:28 IST" duration-ms="42035" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void ramchavantestautomation.Tests.SampleUnitTest.alwaysPass()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="alwaysPass()[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@489115ef]" started-at="2025-09-13T23:12:28 IST" name="alwaysPass" finished-at="2025-09-13T23:12:28 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- alwaysPass -->
        <test-method is-config="true" signature="captureResult(org.testng.ITestResult)[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@489115ef]" started-at="2025-09-13T23:12:28 IST" name="captureResult" finished-at="2025-09-13T23:13:11 IST" duration-ms="42157" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=alwaysPass status=SUCCESS method=SampleUnitTest.alwaysPass()[pri:0, instance:ramchavantestautomation.Tests.SampleUnitTest@489115ef] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureResult -->
      </class> <!-- ramchavantestautomation.Tests.SampleUnitTest -->
    </test> <!-- Chrome Tests -->
  </suite> <!-- Ecommerce Automation Suite -->
</testng-results>
